name: churn_prediction
services:
  streamlit:
    build: docker/streamlit
    image: prasetyowidyantoro/ml_process_streamlit
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8501:8501
    volumes:
      - ./:/home/
  api:
    build: docker/api
    image: prasetyowidyantoro/ml_process_api
    container_name: api_backend
    ports:
      - 8000:8000
    volumes:
      - ./:/home/